server:
  port: 8080

spring:
  application:
    name:registration-api
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:mydb
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

via-cep:
  api:
    base-url: ${VIA_CEP_BASE_URL}
